# Generated by Django 5.1.3 on 2024-11-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livro',
            new_name='PesquisaResposta',
        ),
    ]
