# Generated by Django 5.1.3 on 2024-11-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbQuestionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.IntegerField()),
                ('questao_1', models.IntegerField()),
                ('questao_2', models.IntegerField()),
                ('questao_3', models.IntegerField()),
                ('questao_4', models.IntegerField()),
                ('questao_5', models.IntegerField()),
                ('questao_6', models.IntegerField()),
                ('questao_7', models.IntegerField()),
                ('questao_8', models.TextField()),
                ('questao_9', models.TextField()),
                ('questao_10', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_questionario',
                'ordering': ['id'],
            },
        ),
    ]
